services:
  ayon-mcp:
    environment:
      AYON_MCP_OTEL_ENABLED: "true"
    networks:
      - default
      - ayon-observability

networks:
  ayon-observability:
    name: ayon-observability
    external: true
